name: Commit SDK
on:
  workflow_call:
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: sdk
      - name: Commit
        working-directory: ./sdk
        run: |
          git config --global user.email "oss@expediagroup.com"
          git config --global user.name "Expedia Group Open Source"
          go install resenje.org/casbab/cmd/casbab@latest
          git checkout -b "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          rm -rf "${GITHUB_WORKSPACE}"/release
          mkdir -p "${GITHUB_WORKSPACE}"/release/
          tar -xzf *.tar.gz
          rm *.tar.gz
          mkdir -p  ${GITHUB_WORKSPACE}/release/"${{github.event.inputs.name}}"
          mv *  ${GITHUB_WORKSPACE}/release/"${{github.event.inputs.name}}"
          git add "${GITHUB_WORKSPACE}"/release/\*
          git commit -m "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          git push --set-upstream origin "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          gh pr create -B main -H "${{github.event.inputs.name}}-${{github.event.inputs.version}}" --title 'chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK' --fill
        env:
          GH_TOKEN: ${{ github.token }}
