name: Generate and Publish Sources
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: expediagroup/sdk/generator/package
      - uses: actions/download-artifact@v3
        with:
          name: specs
          path: expediagroup/sdk/generator/package
      - name: Publish Code
        working-directory: expediagroup/sdk/generator/package
        run: |
          git config --global user.email "oss@expediagroup.com"
          git config --global user.name "Expedia Group Open Source"
          rm -rf ../../../../release/"${{github.event.inputs.name}}"
          mkdir -p ../../../../release/"${{github.event.inputs.name}}"
          tar -xzf *.tar.gz
          rm *.tar.gz
          find ./ -name \*.py -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/ \;
          find ./ -name \*.yaml -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/ \;
          git fetch --depth=1 origin main
          git checkout -b "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          git add ../../../../release/\*
          cd ../../../..
          pip install -r requirements.txt
          black .
          cd -
          git commit -m "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          git push --set-upstream origin "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          gh pr create -B main -H "${{github.event.inputs.name}}-${{github.event.inputs.version}}" --title 'chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK' --fill
        env:
          GH_TOKEN: ${{ github.token }}
