name: Generate and Publish SDK
on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Generated SDK version'
        required: true
        default: ''
      name:
        description: 'Generated SDK name'
        required: true
      fileAsBase64:
        description: 'Generated SDK file as base64 encoded'
        required: true
      test:
        description: 'Release to test?'
        required: false
jobs:
  generate_sdk:
    uses: ./.github/workflows/generate-sdk.yaml
    with:
      version: ${{ github.event.inputs.version }}
      name: ${{ github.event.inputs.name }}
      fileAsBase64: ${{ github.event.inputs.fileAsBase64 }}
  commit_sdk:
    needs: [ generate_sdk ]
    uses: ./.github/workflows/commit-sdk.yaml
  publish_sdk:
    needs: [ generate_sdk ]
    uses: ./.github/workflows/publish-sdk.yaml
    secrets: inherit
    with:
      test: ${{ github.event.inputs.test }}
