name: Generate and Publish Sources
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: expediagroup/sdk/generator/package
      - uses: actions/download-artifact@v3
        with:
          name: specs
          path: expediagroup/sdk/generator/package
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: expediagroup/sdk/generator/package/docs
      - name: Prepare Code
        working-directory: expediagroup/sdk/generator/package
        run: |
          rm -rf ../../../../release/"${{github.event.inputs.name}}"
          mkdir -p ../../../../release/"${{github.event.inputs.name}}/src"
          tar -xzf *.tar.gz
          rm *.tar.gz
          cp -r ./docs ../../../../release/"${{github.event.inputs.name}}"/
          find ./ -name \*.py -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/src/ \;
          find ./ -name \*.yaml -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/src/ \;
      - name: Format Code
        run: |
          pip3 install -r requirements-dev.txt
          docformatter --recursive --black --in-place --close-quotes-on-newline release
          isort release
          black release
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          commit-message: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          title: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          add-paths: |
            release/*
