name: Generate and Publish Sources
on:
  workflow_call:
    inputs:
      name:
        description: 'SDK Name'
        required: true
        type: string
      version:
        description: 'SDK Version'
        required: true
        type: string

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: expediagroup/sdk/generator/package
      - uses: actions/download-artifact@v3
        with:
          name: specs
          path: expediagroup/sdk/generator/package
      - uses: actions/download-artifact@v3
        with:
          name: docs
          path: expediagroup/sdk/generator/package
      - name: Publish Code
        working-directory: expediagroup/sdk/generator/package
        run: |
          rm -rf ../../../../release/"${{github.event.inputs.name}}"
          mkdir -p ../../../../release/"${{github.event.inputs.name}}"
          tar -xzf *.tar.gz
          rm *.tar.gz
          echo "separator"
          pwd
          ls
          echo "separator"
          cp -r ./docs ../../../../release/"${{github.event.inputs.name}}"/
          find ./ -name \*.py -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/ \;
          find ./ -name \*.yaml -exec cp {} ../../../../release/"${{github.event.inputs.name}}"/ \;
          cd ../../../..
          pip install -r ../../../../requirements-dev.txt
          black .
          cd -
      - name: Create PR
        uses: peter-evans/create-pull-request@v5
        with:
          branch: "${{github.event.inputs.name}}-${{github.event.inputs.version}}"
          commit-message: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          title: "chore: Publish ${{github.event.inputs.name}} [${{github.event.inputs.version}}] SDK"
          add-paths: |
            release/*
