name: Publish SDK
on:
  workflow_call:
    inputs:
      test:
        description: 'Release to test?'
        required: false
        type: string
jobs:
  job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v3
        with:
          name: sdk
          path: sdk
      - name: Publish to PyPI
        if: "${{ github.event.inputs.test == '' }}"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PY_PI_TOKEN }}
          packages_dir: sdk
      - name: Publish to Test PyPI
        if: "${{ github.event.inputs.test != '' }}"
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PY_PI_TOKEN }}
          packages_dir: sdk
