name: Publish SDK
on:
  workflow_call:
    inputs:
      production_release:
        description: 'Release to production'
        required: true
        type: boolean
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: sdk
          path: sdk
      - name: Publish to PyPI
        if: ${{ github.event.inputs.production_release == 'true' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          password: ${{ secrets.PY_PI_TOKEN }}
          packages_dir: sdk
      - name: Publish to Test PyPI
        if: ${{ github.event.inputs.production_release == 'false' }}
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          password: ${{ secrets.TEST_PY_PI_TOKEN }}
          packages_dir: sdk
